name: Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        - uses: action/checkout@v3
        - name: Listar todos os arquivos do projeto
          run: ls- la